Add task entity to rest server
DVitushkin/Vitushkin_Todo_List pull request #1
Opened 2023-12-19 12:46 UTC by DVitushkin

2023-12-19 17:48 UTC, MVlasovD requested changes

2023-12-19 17:48 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/exception/ExceptionApiHandler.java
> +
а автотесты проходят?

2023-12-19 17:48 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/dto/CreateTodoDto.java
> +    @Size(min = 3, max = 160)
сообщение ошибки?

используй материалы в репо обучения, там есть 2 файла с ошибками и константами для валидации

2023-12-19 17:48 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/controller/TaskController.java
> +    public TaskController(TaskService service) {
ломбок?

2023-12-19 17:48 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/controller/TaskController.java
> +    @Autowired
эту аннотацию можно опустить

2023-12-19 17:48 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/controller/TaskController.java
> +        task.setText(createTodoDto.getText());
это логика для сервиса

2023-12-19 17:48 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/controller/TaskController.java
> +        return new BaseSuccessResponse(200, true);
магические числа
ответ нужно отдавать на клиент с помощью респонсэнтити

2023-12-19 17:48 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/controller/TaskController.java
> +        service.updateStatusForAll(changeStatusTodoDto.isStatus());
логика для сервиса

2023-12-19 17:48 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/controller/TaskController.java
> +        return new BaseSuccessResponse(200, true);
?

2023-12-19 17:48 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/controller/TaskController.java
> +        return new CustomSuccessResponse<>(200, true, getNewsDto);
респонсэнтити

2023-12-19 17:48 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/controller/TaskController.java
> +        return new BaseSuccessResponse(200, true);
?

2023-12-19 17:48 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/service/TaskService.java
> +
```suggestion
```

2023-12-22 08:03 UTC, MVlasovD requested changes

2023-12-22 08:03 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/controller/TaskController.java
> +    @Autowired
и модификатора доступа нет?

2023-12-22 08:03 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/dto/taskDto/CreateTodoDto.java
> +    @Size(min = 3, max = 160, message = "size not valid")
не ставь в сообщение строку, у  тебя же есть инам и интерфейс с константами для этого,
исправь это везде

2023-12-22 08:03 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/dto/taskDto/GetPaginatedTaskDto.java
> +    @Min(value = 1, message = "tasks per page greater or equal 1")
message?

2023-12-22 08:03 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/exception/ExceptionApiHandler.java
> +
?

2023-12-22 08:03 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/exception/ExceptionApiHandler.java
> +    }
вроде не надо это обрабатывать

2023-12-22 08:03 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/response/ErrResponse.java
> +public class ErrResponse implements AbstractErrorResponse {
это всё можно делать и в CustomSuccessResponse

2023-12-22 08:03 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/response/MultiErrorResponse.java
> +public class MultiErrorResponse implements AbstractErrorResponse {
это всё можно делать и в CustomSuccessResponse
и не создавать еще классов

2023-12-22 08:03 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/service/TaskService.java
> +        return new CustomSuccessResponse<>(repository.save(task), 0, true);
магические числа !

2023-12-22 08:03 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/service/TaskService.java
> +        return new BaseSuccessResponse(200, true);
опять магия

2023-12-22 08:03 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/service/TaskService.java
> +        return new BaseSuccessResponse(200, true);
магические числа

2023-12-22 08:03 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/service/TaskService.java
> +        return new BaseSuccessResponse(200, true);
!

2023-12-25 09:54 UTC, MVlasovD requested changes

2023-12-25 09:54 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/dto/taskDto/GetPaginatedTaskDto.java
> +public class GetPaginatedTaskDto {
разве есть такое дто в доках?

2023-12-25 09:54 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/exception/ExceptionApiHandler.java
> +
вопрос остается в силе, тесты проходят все?

2023-12-25 09:54 UTC, MVlasovD commented on src/main/java/DVitushkin/Vitushkin_Todo_List/controller/TaskController.java
> +    public ResponseEntity<CustomSuccessResponse<GetNewsDto>> getPaginated(@Validated GetPaginatedTaskDto getPaginatedTaskDto) {
там параметры данного метода в доках иные

2023-12-25 10:03 UTC, DVitushkin commented on src/main/java/DVitushkin/Vitushkin_Todo_List/dto/taskDto/GetPaginatedTaskDto.java
> +public class GetPaginatedTaskDto {
в доке они указанны просто как параметры, но я проверил и ДТО это тоже съедает, также как json body

2024-01-10 11:49 UTC, MVlasovD approved these changes

2024-01-10 11:50 UTC, merged